# Generated by Django 6.0.5 on 2026-05-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('sinopse', models.CharField(max_length=100)),
                ('duracao', models.IntegerField()),
                ('ano_lancamento', models.IntegerField()),
            ],
        ),
    ]
