# Generated by Django 6.0.6 on 2026-06-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MH_Cine', '0004_perfil_email_confirmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/'),
        ),
    ]
