# Generated by Django 6.0.6 on 2026-06-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MH_Cine', '0006_alter_filme_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='nota',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
