# Generated by Django 6.0.6 on 2026-06-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MH_Cine', '0007_filme_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='genero',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
