# Generated by Django 6.0.5 on 2026-05-08 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MH_Cine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='ano_lancamento',
        ),
        migrations.AddField(
            model_name='filme',
            name='data_lancamento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filme',
            name='sinopse',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='filme',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
