# Generated by Django 6.0.5 on 2026-05-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MH_Cine', '0003_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='email_confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
