# Generated by Django 6.0.6 on 2026-06-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MH_Cine', '0005_filme_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='capas/'),
        ),
    ]
