# Generated by Django 6.0.6 on 2026-06-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MH_Cine', '0008_filme_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='classificacao',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
