# Generated by Django 6.0.6 on 2026-06-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MH_Cine', '0009_filme_classificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='classificacao',
            field=models.CharField(max_length=100),
        ),
    ]
